# Generated by Django 4.2.7 on 2023-11-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('updated_on', models.DateField(auto_now=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=500)),
                ('desc', models.TextField(blank=True, default='', max_length=2000)),
            ],
        ),
    ]
